x-veld:
  code:

services:
  veld:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./src:/home/docker_user/
    working_dir: /home/docker_user/
    command: jupyter notebook --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password=''

