x-veld:
  code:
    description: "A statistical summary on conllu data, to count linguistic features of a conllu 
      file:
      - count of total tokens 
      - count of total lemma
      - count of lemma normalized by token (to put the lemma in relation with token)
      - count of occurrence of each (Universal Dependencies) part of speech tag
      Can be adapted to other use cases and made more flexible, but is primarily used in this chain 
      veld: https://github.com/veldhub/veld_chain__eltec_udpipe_inference"
    topic:
      - "NLP"
      - "Machine Learning"
      - "Tokenization"
      - "Lemmatization"
      - "Part Of Speech"
      - "Dependency Parsing"
      - "Universal Dependencies"
      - "Grammatical Annotation"

    input:
      - volume: "/veld/input/"
        file_type: "conllu"

    output:
      - volume: "/veld/output/"
        file_type: "json"
        content: 
          - "statistics"
          - "NLP statistics"

services:
  veld:
    build: .
    command: jupyter notebook --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888
    working_dir: /veld/code/
    volumes:
      - ./src:/veld/code/

