x-veld:
  code:
    description: ""
    topic:
      - "NLP"
      - "Machine Learning"
      - "Tokenization"
      - "Lemmatization"
      - "Part Of Speech"
      - "Dependency Parsing"
      - "Universal Dependencies"
      - "Grammatical Annotation"

    input:
      - volume: "/veld/input/"
        file_type: "conllu"

    output:
      - volume: "/veld/output/"
        file_type: "json"
        content: 
          - "statistics"
          - "NLP statistics"

services:
  veld:
    build: .
    command: jupyter notebook --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888
    working_dir: /veld/code/
    volumes:
      - ./src:/veld/code/

